name: Deploy HybridRAG

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy CloudFormation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v2
        with:
          name: HybridRAGStack
          template: infrastructure/cloudformation.yml
          capabilities: CAPABILITY_NAMED_IAM
